"""Add permintaan_barang table

Revision ID: aa9e20692c51
Revises: add_total_barang
Create Date: 2026-03-05 08:31:08.109849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa9e20692c51'
down_revision = 'add_total_barang'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permintaan_barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pengguna', sa.String(length=255), nullable=False),
    sa.Column('nama_barang1', sa.String(length=255), nullable=False),
    sa.Column('banyaknya1', sa.Integer(), nullable=False),
    sa.Column('nama_barang2', sa.String(length=255), nullable=True),
    sa.Column('banyaknya2', sa.Integer(), nullable=True),
    sa.Column('nama_barang3', sa.String(length=255), nullable=True),
    sa.Column('banyaknya3', sa.Integer(), nullable=True),
    sa.Column('tempat_penggunaan', sa.String(length=255), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('merk_kontrak')
    with op.batch_alter_table('aset_tetap', schema=None) as batch_op:
        batch_op.alter_column('total_barang',
               existing_type=mysql.INTEGER(),
               comment='Total jumlah barang',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('laporan_kerusakan', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_aset_tetap_id'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_created_at'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_pelapor_id'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_status'))
        batch_op.create_index(batch_op.f('ix_laporan_kerusakan_aset_tetap_id'), ['aset_tetap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laporan_kerusakan_pelapor_id'), ['pelapor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan_kerusakan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laporan_kerusakan_pelapor_id'))
        batch_op.drop_index(batch_op.f('ix_laporan_kerusakan_aset_tetap_id'))
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_pelapor_id'), ['pelapor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_aset_tetap_id'), ['aset_tetap_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('aset_tetap', schema=None) as batch_op:
        batch_op.alter_column('total_barang',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total jumlah barang',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    op.create_table('merk_kontrak',
    sa.Column('merk_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kontrak_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kontrak_id'], ['kontrak_barang.id'], name=op.f('merk_kontrak_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merk_id'], ['merk_barang.id'], name=op.f('merk_kontrak_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merk_id', 'kontrak_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('permintaan_barang')
    # ### end Alembic commands ###
