"""add total_barang to aset_tetap

Revision ID: add_total_barang
Revises: d90c272f157b
Create Date: 2026-01-26

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_total_barang'
down_revision = 'd90c272f157b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aset_tetap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_barang', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aset_tetap', schema=None) as batch_op:
        batch_op.drop_column('total_barang')

    # ### end Alembic commands ###
