"""init migrations

Revision ID: d90c272f157b
Revises: 
Create Date: 2026-01-20 14:51:48.278022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd90c272f157b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merk_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipe', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tanggal_pengadaan', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nomor_kontrak', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spesifikasi', sa.Text(), nullable=True))
        batch_op.drop_column('deskripsi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merk_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi', mysql.TEXT(), nullable=True))
        batch_op.drop_column('spesifikasi')
        batch_op.drop_column('nomor_kontrak')
        batch_op.drop_column('tanggal_pengadaan')
        batch_op.drop_column('tipe')

    # ### end Alembic commands ###
