"""Update permintaan_barang to use barang_id instead of nama_barang

Revision ID: ed6a2c2bbc66
Revises: aa9e20692c51
Create Date: 2026-03-05 08:38:45.113670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed6a2c2bbc66'
down_revision = 'aa9e20692c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan_kerusakan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_aset_tetap_id'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_created_at'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_pelapor_id'))
        batch_op.drop_index(batch_op.f('idx_laporan_kerusakan_status'))
        batch_op.create_index(batch_op.f('ix_laporan_kerusakan_aset_tetap_id'), ['aset_tetap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laporan_kerusakan_pelapor_id'), ['pelapor_id'], unique=False)

    with op.batch_alter_table('permintaan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barang1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('barang2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('barang3_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barang', ['barang3_id'], ['id'])
        batch_op.create_foreign_key(None, 'barang', ['barang2_id'], ['id'])
        batch_op.create_foreign_key(None, 'barang', ['barang1_id'], ['id'])
        batch_op.drop_column('nama_barang1')
        batch_op.drop_column('nama_barang2')
        batch_op.drop_column('nama_barang3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permintaan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_barang3', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('nama_barang2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('nama_barang1', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barang3_id')
        batch_op.drop_column('barang2_id')
        batch_op.drop_column('barang1_id')

    with op.batch_alter_table('laporan_kerusakan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laporan_kerusakan_pelapor_id'))
        batch_op.drop_index(batch_op.f('ix_laporan_kerusakan_aset_tetap_id'))
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_pelapor_id'), ['pelapor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_laporan_kerusakan_aset_tetap_id'), ['aset_tetap_id'], unique=False)

    # ### end Alembic commands ###
